// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjLDIMGwWVYK2a7BL186jYaGBYtJCO-k',
    appId: '1:532876534894:web:4d32ec0bb5f12e4fae727f',
    messagingSenderId: '532876534894',
    projectId: 'kids-quiz-mono',
    authDomain: 'kids-quiz-mono.firebaseapp.com',
    databaseURL: 'https://kids-quiz-mono.firebaseio.com',
    storageBucket: 'kids-quiz-mono.appspot.com',
    measurementId: 'G-9P3BNVWP43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBegesend-snNi9xCze8mhWT0ufS_MzfcE',
    appId: '1:532876534894:android:7c3994612ad39536ae727f',
    messagingSenderId: '532876534894',
    projectId: 'kids-quiz-mono',
    databaseURL: 'https://kids-quiz-mono.firebaseio.com',
    storageBucket: 'kids-quiz-mono.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVhLZ58P4ki0iwSb-Pvv70PPn5n8r718Q',
    appId: '1:532876534894:ios:744584e044535bf8ae727f',
    messagingSenderId: '532876534894',
    projectId: 'kids-quiz-mono',
    databaseURL: 'https://kids-quiz-mono.firebaseio.com',
    storageBucket: 'kids-quiz-mono.appspot.com',
    iosClientId: '532876534894-o4pqvrju5ah9bdlr0ceg3l026i1p4bpd.apps.googleusercontent.com',
    iosBundleId: 'com.mono0926.kidsquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVhLZ58P4ki0iwSb-Pvv70PPn5n8r718Q',
    appId: '1:532876534894:ios:744584e044535bf8ae727f',
    messagingSenderId: '532876534894',
    projectId: 'kids-quiz-mono',
    databaseURL: 'https://kids-quiz-mono.firebaseio.com',
    storageBucket: 'kids-quiz-mono.appspot.com',
    iosClientId: '532876534894-o4pqvrju5ah9bdlr0ceg3l026i1p4bpd.apps.googleusercontent.com',
    iosBundleId: 'com.mono0926.kidsquiz',
  );
}
