# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  errors:
    # https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/firebase_options.dart
  plugins:
    - custom_lint
