name: kidsquiz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  audioplayers:
  cloud_firestore:
  collection:
  confetti:
  cupertino_icons:
  extended_image:
  firebase_analytics: any
  firebase_app_check: any
  firebase_auth: any
  firebase_core:
  firebase_crashlytics:
  firebase_dynamic_links: any
  firebase_in_app_messaging: any
  firebase_messaging: any
  firebase_performance: any
  firebase_remote_config: any
  firebase_storage: any
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_riverpod:
  flutter_tts:
  freezed_annotation:
  gap:
  go_router: any
  hooks_riverpod:
  io:
  json_annotation:
  json_converter_helper:
  mono_kit:
  path:
  riverpod:
  simple_logger:
  web_browser_detect:
dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed: any
  grinder: any
  json_serializable:
  pedantic_mono:
dependency_overrides:
  flutter_riverpod: '>=2.0.0-dev'
flutter:
  uses-material-design: true
  assets:
    - assets/sound/
