name: kids_quiz
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.14.6 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  freezed_annotation:
  mono_kit:
  pedantic_mono:
  provider:
  flutter_tts:
  vsync_provider:
  audioplayers:
  confetti:
    git: https://github.com/mono0926/flutter_confetti.git
  disposable_provider:
  cached_network_image:
  firestore_ref: ^0.8.0-dev
  image_picker:
  permission_handler:
  image_cropper:
  json_annotation:
  firebase_storage:
  rxdart:
  collection:
  flutter_image_compress:
  google_sign_in:
  google_sign_in_web:
  firebase_auth:
  firebase_auth_web:
  flutter_auth_buttons:
dependency_overrides:
  provider: 4.1.0-dev
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: any
  json_serializable: any
flutter:
  uses-material-design: true
  assets:
    - assets/sound/